### ISSUE TITLE
Samples for vhost configurations are wrong

### ISSUE THREAD

**Issue by wasfree** [tcpcloud/salt-formula-rabbitmq#42]
On the README.rst example pillars configuration host/policy is described like this:

```
    virtual_hosts:
    - enabled: true
      host: '/monitor'
      user: 'monitor'
      password: 'password'
      policies:
      - name: HA
        pattern: '^(?!amq\.).*'
        definition: '{"ha-mode": "all"}'
```

but should look like this:

```
    host:
      '/monitor':
        enabled: true
        user: 'monitor'
        password: 'password'
        policies:
        - name: HA
          pattern: '^(?!amq\.).*'
          definition: '{"ha-mode": "all"}'
```
